apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4413-go-helloworld-2:3bc0211c4db7cc697399993db5609b5ba30e6330
          name: go-helloworld-2
