name: "Build"
on:
  push:
    paths-ignore:
      - "manifests/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/2022-4400-exp/4413-go-helloworld-2:${{ github.sha }}
            ghcr.io/2022-4400-exp/4413-go-helloworld-2:latest

      - name: Update manifest image tag
        id: update-image-tag
        continue-on-error: true
        run: |
          yq eval '.spec.template.spec.containers[0].image = "ghcr.io/2022-4400-exp/4413-go-helloworld-2:"+env(GITHUB_SHA)' -i ./manifests/deployment.yaml
          git diff --name-only --exit-code

      - name: Commit/Push manifest
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update image tag to $GITHUB_SHA"
          git push
